### ISSUE TITLE
can't get a good output

### ISSUE THREAD

**Issue by buyaoxiaozhu** [jsn5/dancenet#3]
Thank you  for sharing~
I have used the pre-training model many times, but  can't get a good video. I often get some videos of convulsions and loops.
Does anyone know why?

**Comment by jsn5** [comment]
Hey @buyaoxiaozhu, sorry for the late reply. You can try tweaking the temperature variable given in the 'generate video' section of [dancegen.ipynb](https://github.com/jsn5/dancenet/blob/master/dancegen.ipynb) to get better results.
